# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('domicilio', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
