# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
